package Login;
import Vista.FrmProducto;
import Utilidades.HashUtil;
import java.sql.*;
import javax.swing.JOptionPane;

public class LoginInicio extends javax.swing.JFrame {
    
    private static final String ADMIN_HASH = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9";

    public LoginInicio() {
    initComponents();
    configurarBotones();
    setLocationRelativeTo(null);
    
    // LIMPIAR CAMPOS (IMPORTANTE)
    Usuario.setText("");
    Password.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jDialog1 = new javax.swing.JDialog();
        panelLogin = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        Usuario = new java.awt.TextField();
        btnInSe = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBackground(new java.awt.Color(22, 20, 20));

        text1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setText("Iniciar seción");

        Usuario.setBackground(new java.awt.Color(51, 51, 51));
        Usuario.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        Usuario.setForeground(new java.awt.Color(102, 102, 102));
        Usuario.setName(""); // NOI18N
        Usuario.setText("usuario1");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        btnInSe.setBackground(new java.awt.Color(82, 252, 135));
        btnInSe.setText("Iniciar seción");

        btnReg.setBackground(new java.awt.Color(81, 232, 187));
        btnReg.setText("Registrarse");

        text2.setBackground(new java.awt.Color(255, 255, 255));
        text2.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        text2.setForeground(new java.awt.Color(153, 153, 153));
        text2.setText("Contraseña");

        text3.setBackground(new java.awt.Color(255, 255, 255));
        text3.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        text3.setForeground(new java.awt.Color(153, 153, 153));
        text3.setText("Usuario");

        Password.setBackground(new java.awt.Color(51, 51, 51));
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("jPasswordField1");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text3)
                    .addComponent(text2)
                    .addComponent(btnReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInSe, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(text1)
                    .addComponent(Password)
                    .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnInSe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void configurarBotones() {
        btnInSe.addActionListener(evt -> btnInSeActionPerformed());
        btnReg.addActionListener(evt -> btnRegActionPerformed());
        Password.addActionListener(evt -> btnInSeActionPerformed()); // ENTER = login
    }

    private void btnInSeActionPerformed() {
        String usuario = Usuario.getText().trim();
        String contraseña = new String(Password.getPassword()).trim();

        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete ambos campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = conexionBD.ConexionBD.conectar();
             PreparedStatement ps = conn.prepareStatement("SELECT contraseña FROM usuarios WHERE usuario = ?")) {

            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String hashBD = rs.getString("contraseña");
                if (HashUtil.hashSHA256(contraseña).equals(hashBD)) {
                    this.dispose();
                    new FrmProducto().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
        }
    }

    private void btnRegActionPerformed() {
        String adminPass = JOptionPane.showInputDialog(this, "Contraseña de administrador:", "Autorización", JOptionPane.PLAIN_MESSAGE);
    if (adminPass == null || !HashUtil.hashSHA256(adminPass).equals(ADMIN_HASH)) {
        JOptionPane.showMessageDialog(this, "Acceso denegado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String nuevoUsuario = JOptionPane.showInputDialog(this, "Nuevo usuario:");
    if (nuevoUsuario == null || nuevoUsuario.trim().isEmpty()) return;
    String nuevaPass = JOptionPane.showInputDialog(this, "Nueva contraseña:");
    if (nuevaPass == null || nuevaPass.trim().isEmpty()) return;
    try (Connection conn = conexionBD.ConexionBD.conectar();
         PreparedStatement ps = conn.prepareStatement("INSERT INTO usuarios (usuario, contraseña) VALUES (?, ?)")) {
        ps.setString(1, nuevoUsuario.trim());
        ps.setString(2, HashUtil.hashSHA256(nuevaPass));
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Usuario creado con éxito.");
        limpiarCampos();
    } catch (SQLException e) {
        if (e.getMessage().contains("Duplicate entry")) {
            JOptionPane.showMessageDialog(this, "El usuario ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }
    }
    }

    private void limpiarCampos() {
        Usuario.setText("");
        Password.setText("");
    }
    
    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private java.awt.TextField Usuario;
    private javax.swing.JButton btnInSe;
    private javax.swing.JButton btnReg;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
