
package Vista;
import controlador.ControladorProducto;
import Producto.Producto;
import Utilidades.ReportePDF;
import Utilidades.Validaciones;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import java.util.Date;


public class FrmProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProducto.class.getName());

    
    public FrmProducto() {
        initComponents();
        cargarTabla();
        configurarTabla();
        restaurarBotonAgregar(); // Ya funciona
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        NomTxt = new javax.swing.JTextField();
        StockTxt = new javax.swing.JTextField();
        PreTxt = new javax.swing.JTextField();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        Titulo5 = new javax.swing.JLabel();
        Titulo6 = new javax.swing.JLabel();
        DesTxt = new javax.swing.JTextField();
        BarrasTxt = new javax.swing.JTextField();
        BtnEdit = new javax.swing.JComboBox<>();
        tablaProductos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nota1 = new javax.swing.JLabel();
        Titulo7 = new javax.swing.JLabel();
        GenRep = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 235, 206));

        BtnAgregar.setBackground(new java.awt.Color(255, 0, 51));
        BtnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("+ Nuevo");
        BtnAgregar.setBorder(null);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        NomTxt.setBackground(new java.awt.Color(51, 51, 51));
        NomTxt.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NomTxt.setForeground(new java.awt.Color(153, 153, 153));
        NomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomTxtActionPerformed(evt);
            }
        });

        StockTxt.setBackground(new java.awt.Color(51, 51, 51));
        StockTxt.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        StockTxt.setForeground(new java.awt.Color(153, 153, 153));

        PreTxt.setBackground(new java.awt.Color(51, 51, 51));
        PreTxt.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        PreTxt.setForeground(new java.awt.Color(153, 153, 153));
        PreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreTxtActionPerformed(evt);
            }
        });

        Titulo1.setBackground(new java.awt.Color(0, 0, 0));
        Titulo1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Gestor de Productos Heladería \"Sugar\"");

        Titulo2.setBackground(new java.awt.Color(0, 0, 0));
        Titulo2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(153, 153, 153));
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("Nombre del Producto");

        Titulo3.setBackground(new java.awt.Color(0, 0, 0));
        Titulo3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(153, 153, 153));
        Titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo3.setText("Precio");

        Titulo4.setBackground(new java.awt.Color(0, 0, 0));
        Titulo4.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(153, 153, 153));
        Titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo4.setText("Stock");

        Titulo5.setBackground(new java.awt.Color(0, 0, 0));
        Titulo5.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(153, 153, 153));
        Titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo5.setText("Código de barras");

        Titulo6.setBackground(new java.awt.Color(0, 0, 0));
        Titulo6.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Titulo6.setForeground(new java.awt.Color(153, 153, 153));
        Titulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo6.setText("Descripción");

        DesTxt.setBackground(new java.awt.Color(51, 51, 51));
        DesTxt.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        DesTxt.setForeground(new java.awt.Color(153, 153, 153));

        BarrasTxt.setBackground(new java.awt.Color(51, 51, 51));
        BarrasTxt.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        BarrasTxt.setForeground(new java.awt.Color(153, 153, 153));

        BtnEdit.setBackground(new java.awt.Color(255, 0, 51));
        BtnEdit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BtnEdit.setForeground(new java.awt.Color(255, 255, 255));
        BtnEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualizar", "Eliminar" }));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        tablaProductos.setBackground(new java.awt.Color(204, 204, 204));
        tablaProductos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setViewportView(jTable1);

        Nota1.setBackground(new java.awt.Color(0, 0, 0));
        Nota1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Nota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nota1.setText("Selecciona la fila para editar su contenido");

        Titulo7.setBackground(new java.awt.Color(0, 0, 0));
        Titulo7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Titulo7.setForeground(new java.awt.Color(255, 255, 255));
        Titulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo7.setText("LISTA DE PRODUCTOS REGISTRADOS");

        GenRep.setBackground(new java.awt.Color(255, 0, 51));
        GenRep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GenRep.setForeground(new java.awt.Color(255, 255, 255));
        GenRep.setText("Generar Reporte");
        GenRep.setBorder(null);
        GenRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablaProductos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(NomTxt))
                            .addComponent(GenRep, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(StockTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Titulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenRep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // === 1. BtnAgregarActionPerformed() ===

            int row = jTable1.getSelectedRow();
            if (row != -1) {
                JOptionPane.showMessageDialog(this,
                    "Para agregar un NUEVO producto, primero LIMPIE los campos o presione ESC.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nombre = NomTxt.getText().trim();
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
                return;
            }

            // ORDEN CORREGIDO SEGÚN EL LAYOUT REAL
            double precio = Validaciones.veriDoublePositivo(StockTxt.getText().trim(), "Precio");     // ← Precio está en StockTxt
            int stock = Validaciones.veriEnteroPositivo(BarrasTxt.getText().trim(), "Stock");         // ← Stock está en BarrasTxt
            int barras = 0;
            String barrasStr = PreTxt.getText().trim();  // ← Código de barras está en PreTxt
            if (!barrasStr.isEmpty()) {
                barras = Validaciones.veriEnteroPositivo(barrasStr, "Código de barras");
                if (barras <= 0) return;
            }
            String desc = DesTxt.getText().trim();

            Producto p = new Producto(0, nombre, precio, stock, barras, desc);
            if (ControladorProducto.crear(p)) {
                limpiarCampos();
                cargarTabla();
            }

    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void NomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomTxtActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.");
            return;
        }

        int id = (int) jTable1.getValueAt(row, 0);
        String opcion = (String) BtnEdit.getSelectedItem();

        if ("Actualizar".equals(opcion)) {
            actualizarProducto(id);
        } else if ("Eliminar".equals(opcion)) {
            eliminarProducto(id);
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void PreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreTxtActionPerformed

    private void GenRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenRepActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File("Reporte_Sugar_" + 
            new SimpleDateFormat("ddMMyyyy_HHmm").format(new Date()) + ".pdf"));

        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try (FileOutputStream fos = new FileOutputStream(fc.getSelectedFile())) {

                String rutaLogo = "/recursos/logo_sugar.png";  // CLASSPATH

                ReportePDF.generar(fos, rutaLogo);
                JOptionPane.showMessageDialog(this, "Reporte generado:\n" + fc.getSelectedFile().getName());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                e.printStackTrace();
            }
    
}
    }//GEN-LAST:event_GenRepActionPerformed

   private void configurarTabla() {
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    // ASIGNAR EN ORDEN CRUZADO (según layout)
                    NomTxt.setText(jTable1.getValueAt(row, 1).toString());           // Nombre
                    StockTxt.setText(jTable1.getValueAt(row, 2).toString());         // Precio → va a StockTxt
                    BarrasTxt.setText(jTable1.getValueAt(row, 3).toString());        // Stock → va a BarrasTxt
                    PreTxt.setText(jTable1.getValueAt(row, 4).toString());           // Código de barras → va a PreTxt
                    DesTxt.setText(jTable1.getValueAt(row, 5).toString());           // Descripción

                    // Deshabilitar botón
                    BtnAgregar.setEnabled(false);
                    BtnAgregar.setText("Selección activa");

                    // Doble clic = limpiar
                    if (evt.getClickCount() == 2) {
                        limpiarCampos();
                    }
                }
            }
        });

        // ESC = limpiar
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
                    limpiarCampos();
                }
            }
        });
    }
    
    
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nombre", "Precio", "Stock", "Código de Barras", "Descripción"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };

        try (Connection c = conexionBD.ConexionBD.conectar();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM productos")) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("codigoProducto"),
                    rs.getString("nombreProducto"),
                    rs.getDouble("precio"),
                    rs.getInt("cantidad"),
                    rs.getInt("codigoDeBarras"),
                    rs.getString("descripcion")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar: " + e.getMessage());
        }

        jTable1.setModel(modelo);
    }
    
    private void actualizarProducto(int id) {
        String nombre = NomTxt.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return;
        }

        // ORDEN CORREGIDO
        double precio = Validaciones.veriDoublePositivo(StockTxt.getText().trim(), "Precio");
        int stock = Validaciones.veriEnteroPositivo(BarrasTxt.getText().trim(), "Stock");
        int barras = 0;
        String barrasStr = PreTxt.getText().trim();
        if (!barrasStr.isEmpty()) {
            barras = Validaciones.veriEnteroPositivo(barrasStr, "Código de barras");
            if (barras <= 0) return;
        }
        String desc = DesTxt.getText().trim();

        Producto p = new Producto(id, nombre, precio, stock, barras, desc);
        if (ControladorProducto.actualizar(p)) {
            limpiarCampos();
            cargarTabla();
        }
    }
    
    private void eliminarProducto(int id) {
        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Eliminar producto ID " + id + "?",
            "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (ControladorProducto.eliminar(id)) {
                limpiarCampos();
                cargarTabla();
            }
        }
    }

    private void limpiarCampos() {
        NomTxt.setText("");
        PreTxt.setText("");
        StockTxt.setText("");
        BarrasTxt.setText("");
        DesTxt.setText("");
        jTable1.clearSelection();
        restaurarBotonAgregar();
    }
    
    private void restaurarBotonAgregar() {
        BtnAgregar.setEnabled(true);
        BtnAgregar.setText("+ Nuevo");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarrasTxt;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JComboBox<String> BtnEdit;
    private javax.swing.JTextField DesTxt;
    private javax.swing.JButton GenRep;
    private javax.swing.JTextField NomTxt;
    private javax.swing.JLabel Nota1;
    private javax.swing.JTextField PreTxt;
    private javax.swing.JTextField StockTxt;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JLabel Titulo6;
    private javax.swing.JLabel Titulo7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tablaProductos;
    // End of variables declaration//GEN-END:variables
}
